export const NEW_COUNTDOWN_CREATION_PROCESS = 'NEW_COUNTDOWN_CREATION_PROCESS';
export const NEW_COUNTDOWN_CREATION_PROCESS_COMPLETED = 'NEW_COUNTDOWN_CREATION_PROCESS_COMPLETED';

export const COUNTDOWN_LIST = 'COUNTDOWN_LIST';


export const AUTHORISATION = 'AUTHORISATION';
export const AUTHORISATION_COMPLETE = 'AUTHORISATION_COMPLETE';
